---
language: python
sudo: required

services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible
  - pip install molecule
script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
